### ISSUE TITLE
About cifar10 performance on SimSiam

### ISSUE THREAD

**Issue by kasteric** [Hzzone/ProPos#13]
Hi, I reran the experiments for SimSiam, but I can only achieve around 60% ACC, I am not sure where I was wrong,  could u please share the config file for training SimSiam? Your response is really appreciated!

**Comment by kasteric** [comment]
I have tried many times, including using the .json included in the repo.
![image](https://github.com/Hzzone/ProPos/assets/132050661/b07183da-ab70-4e44-afbb-05596daed432)

**Comment by kasteric** [comment]
Hi, do you have time for sharing the config file for cifar10_simsiam？I have run the experiments multiple times, but the performance is not satisfying. Seems like the representation gets collapsed... Specifically I have replace the projection_num_layers from 3 to 2, and the feat_dim is set to 2048. Is the feat_dim 2048 for k-means too? Thanks so much!
![image](https://github.com/Hzzone/ProPos/assets/132050661/add906f7-329b-4249-9e74-4b4003fda4d2)

**Comment by kasteric** [comment]
> Hi, do you have time for sharing the config file for cifar10_simsiam？I have run the experiments multiple times, but the performance is not satisfying. Seems like the representation gets collapsed... Specifically I have replace the projection_num_layers from 3 to 2, and the feat_dim is set to 2048. Is the feat_dim 2048 for k-means too?
![image](https://user-images.githubusercontent.com/132050661/239511738-add906f7-329b-4249-9e74-4b4003fda4d2.png)

**Comment by Hzzone** [comment]
I have no time to rerun simsiam. There are some important tips on CIFAR if I remember correctly: 1. total bs 512 on single GPU; 2. projection_num_layers=2 instead 3, feat_dim 2048 (for k-means too); 4. weight decay 5e-4

**Comment by Hzzone** [comment]
I have no time to rerun simsiam. There are some important tips on CIFAR if I remember correctly: 1. total bs 512 on single GPU; 2. projection_num_layers=2 instead 3, feat_dim 2048 (for k-means too); 4. weight decay 5e-4

**Comment by kasteric** [comment]
> I have no time to rerun simsiam. There are some important tips on CIFAR if I remember correctly: 1. total bs 512 on single GPU; 2. projection_num_layers=2 instead 3, feat_dim 2048 (for k-means too); 4. weight decay 5e-4

Thanks for your fast and informative response! i will try on single card

**Comment by kasteric** [comment]
Thanks to your guidance! The problem has been solved!
