### ISSUE TITLE
what does the memory data loader do in the basic_template.py?

### ISSUE THREAD

**Issue by ydzhang12345** [Hzzone/ProPos#16]
I am trying to use ProPos on my custom unlabeled data. I believe I will need to rewrite basic_template.py. Can you explain a bit what deos the memory loader do?

**Comment by Hzzone** [comment]
The memory data loader should be used to extract the features for pseudo-labeling without any strong data augmentation. If you need to train on your own unlabeled data, you can refer to https://github.com/Hzzone/ProPos/issues/7. You can also organize the dataset like ImageNet by specifying the data_root.
