### ISSUE TITLE
How to obtain the clustering result after training?

### ISSUE THREAD

**Issue by 4fee8fea** [Hzzone/ProPos#2]
Dear author,

Thanks for sharing the spherical kmeans implementation in [#1](https://github.com/Hzzone/DeepClustering.SSL/issues/1).

What confuses me is how to get the final clustering result after training? Maybe send the features or projections from the target encoder to spherical kmeans clustering again?

Besides, which one of the features or projections from the target encoder should be sent to the spherical kmeans algorithm when generating the pseudo labels?

Thanks for answering!

**Comment by Hzzone** [comment]
The features after projection head from the target encoder (ema-updated one).

**Comment by 4fee8fea** [comment]
Thanks for answering, please excuse my interruption.

Should I get the `final clustering results` via spherical kmeans on the target encoder's features, OR other ways instead?

P.S. The conclusion below is impressive:
> directly using the representations learned by BYOL for k-means clustering outperforms previous work including the contrastive-based ones.

**Comment by Hzzone** [comment]
You are right, you should get the final clustering results via spherical kmeans on the target encoder's features.
