### ISSUE TITLE
Can't Reproduce Result in CIFAR-20

### ISSUE THREAD

**Issue by OBJECT907** [Hzzone/ProPos#4]
I use config/cifar10_r18_propose.yml and only modify 'dataset' to cifar20. But I can't achieve the result in your paper. Is there anything need to change?

**Comment by Hzzone** [comment]
You may need to modify config/cifar20_r18_byol.yml with the changing of parameters cluster_loss_weight and latent_std. I am running this setting, I will upload the pre-trained model and give you feedback as soon as possible.

**Comment by OBJECT907** [comment]
> You may need to modify config/cifar20_r18_byol.yml with the changing of parameters cluster_loss_weight and latent_std. I am running this setting, I will upload the pre-trained model and give you feedback as soon as possible.

Thanks.

**Comment by Hzzone** [comment]
This issue has been solved, and I have updated the pre-trained model in the download link and achieved the same results in my paper.

**Comment by OBJECT907** [comment]
What training parameters need to be changed if I use resnet34?

**Comment by Hzzone** [comment]
Hi, I do not understand what you mean. Could you detail the problem?

**Comment by OBJECT907** [comment]
I simply change **encoder_name** to bigresnet34 in config/cifar10_r18_propose.yml but I got acc 53% (even worse than resnet18). 
Is there any other config I need to change?

**Comment by Hzzone** [comment]
Have you changed the `num_devices`? I will check if the time is available.

**Comment by OBJECT907** [comment]
I trained Propos on 4 RTX 3090 GPUs. `num_devices` is 4.

**Comment by Hzzone** [comment]
> 

You may need to change `config/cifar20_r18_propos.yml`. The training looks like this:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/19267349/217711464-974de08a-3386-4882-aba2-d1ac106fc4f4.png">

**Comment by OBJECT907** [comment]
> > 
> 
> You may need to change `config/cifar20_r18_propos.yml`. The training looks like this: <img alt="image" width="607" src="https://user-images.githubusercontent.com/19267349/217711464-974de08a-3386-4882-aba2-d1ac106fc4f4.png">

This is not the result of CIFAR-20, I guess you upload wrong image. QwQ

**Comment by Hzzone** [comment]
No, it is the result of R34 on CIFAR-10.

**Comment by OBJECT907** [comment]
So how can I train Propos on CIFAR-20 with resnet34?

**Comment by Hzzone** [comment]
> I simply change **encoder_name** to bigresnet34 in config/cifar10_r18_propose.yml but I got acc 53% (even worse than resnet18). Is there any other config I need to change?

Of course, you can. However, you have changed config/cifar10_r18_propos.yml for running on CIFAR-20. I don't know which datasets you would like to train. Also, could you post the details for any questions, otherwise it takes a lot of time.

**Comment by Hzzone** [comment]
I do not understand which datasets you would like to train, since you mentioned you have changed the config/cifar10_r18_propos.yml; that is why I post the training on CIFAR-10. In addition, as I have said above, if you need to train on CIFAR-20, plz change config/cifar20_r18_propos.yml.

**Comment by OBJECT907** [comment]
Sorry. It's my typo. I want to reproduce your result on CIFAR-20 with resnet-34. Do I just need to change the `encoder_name` in `config/cifar20_r18_propose.yml` ?
