### ISSUE TITLE
Training speed of ImageNet-10 

### ISSUE THREAD

**Issue by kasteric** [Hzzone/ProPos#9]
Thanks for your great code bases and fast responses! i just have a minor question regarding the training speed of imagenet-10/imagenet-dogs, which i find is very slow in dataloader processing, causing low gpu utilization. Sorry I am not very familiar with training ImageNet, is this a issue that can be improved or a common phenonmenon? I really appreciate your help!

**Comment by Hzzone** [comment]
Try to use an SSD disk to store your images.

**Comment by kasteric** [comment]
Thanks for your generous response, I found in the paper the training time of CIFAR10 is around 10 hours while that of ImageNet-10 is only 1 hour. However, in my experiments, it took just 3 hours to train CIFAR10 (byol) on 4 RTX 3090 cards for 1000 epochs but it took me more than 5 hours (maybe even longer) to train ImageNet-10, which is very strange, are you using ImageFolder for ImageNet-10?
